# fly.toml app configuration file generated for dj-billyp on 2023-07-11T15:44:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dj-billyp"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
