name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: Raspberry Pi 5
    env:
      APP_DIR: /home/pi/apps/billybot-music

    steps:
    - uses: actions/checkout@v2

    - name: Copy project files to app directory
      run: |
        mkdir -p $APP_DIR
        cp -rf ./{*,.[^.]*} $APP_DIR/ 2>/dev/null || true

    - name: Configure app environment
      run: |
        cd $APP_DIR
        pyenv local 3.10.2
        source myenv/bin/activate
        pip install -r config/requirements.txt

    - name: Install or update systemd service
      run: |
        cat > /tmp/billybot-music.service << EOF
        [Unit]
        Description=billybot-music
        After=network.target

        [Service]
        Type=simple
        User=pi
        WorkingDirectory=$APP_DIR
        ExecStart=python run.py
        Restart=on-failure

        [Install]
        WantedBy=multi-user.target
        EOF
        sudo mv /tmp/billybot-music.service /etc/systemd/system/
        sudo systemctl daemon-reload
        sudo systemctl enable billybot-music.service
        sudo systemctl restart billybot-music.service
        sudo systemctl status billybot-music.service
