name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: raspberry pi 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Copy project files to app directory
      run: |
        mkdir -p $HOME/apps/billybot-music
        cp -rf ./{*,.[^.]*} $HOME/apps/billybot-music/ 2>/dev/null || true

    - name: Configure environment and start app
      working-directory: $HOME/apps/billybot-music
      run: |
        pyenv local 3.10.2
        source myenv/bin/activate
        pip install -r config/requirements.txt
        tmux kill-session -t dj 2>/dev/null || true
        tmux new-session -d -s dj 'python run.py'
