name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: raspberry pi 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Create app directory if it doesn't exist
      run: mkdir -p $HOME/apps/billybot-music

    - name: Copy project files to app directory
      run: cp -rf ./{*,.[^.]*} $HOME/apps/billybot-music/ 2>/dev/null || true

    - name: Set Python version
      working-directory: $HOME/apps/billybot-music
      run: pyenv local 3.10.2

    - name: Activate virtual environment
      working-directory: $HOME/apps/billybot-music
      run: source myenv/bin/activate

    - name: Install dependencies
      working-directory: $HOME/apps/billybot-music
      run: pip install -r config/requirements.txt

    - name: Kill existing tmux session
      run: tmux kill-session -t dj 2>/dev/null || true

    - name: Launch app in new tmux session
      run: tmux new-session -d -s dj 'python run.py'
