name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: raspberry pi 5

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2

    - run: |
        mkdir -p ~/apps/billybot-music/
        cp -rf ./{*,.[^.]*} ~/apps/billybot-music/ 2>/dev/null || true
