name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    environment: raspberry pi 5
    env:
      APP_DIR: /home/pi/apps/billybot-music

    steps:
    - uses: actions/checkout@v2
    
    - name: Create app directory if it doesn't exist
      run: mkdir -p $APP_DIR

    - name: Copy project files to app directory
      run: cp -rf ./{*,.[^.]*} $APP_DIR/ 2>/dev/null || true

    - name: Set Python version locally for app directory
      working-directory: $APP_DIR
      run: pyenv local 3.10.2

    - name: Activate Python virtual environment
      working-directory: $APP_DIR
      run: source myenv/bin/activate

    - name: Install Python package dependencies
      working-directory: $APP_DIR
      run: pip install -r config/requirements.txt

    - name: Kill existing tmux session
      run: tmux kill-session -t dj 2>/dev/null || true

    - name: Launch app in new tmux session
      working-directory: $APP_DIR
      run: tmux new-session -d -s dj 'python run.py'
